---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAqbbmb4doILbV0HTi1GqNIgNu1bd0uD/e4reMpXboe180tM+p/lu+PlCfApWpfad4ZAyVWqCFBAOaFhLUdS8ejvZuQH4Pk1jUo039QTxz0as8ExOgF7fltjlWRgewV7c6qMtc89Z0XnpsC7uUMZuADPxz9J6CTF3B4Iu7HxQhALtcrkaumvYb6t4PJCp+AXgwTrXAHtU87Ye6tcG9TiTOhcx5C7AnF4ek1ar0KBXcN1RG5FIPtdR5uF6xPGzz1i+gUObe7bLJbRl9GsRFnyMMX/AWKgFskqRjBCa7ignKbDtSRED3xfFD+CC6ayhxG8GHtgvMZLDfPEWX861UlwLcupnMn8UUY8pkjeIgXKbMeaxCab/D7I8/V3YQKwBxQMR34KEfXzQ+mhic40GFpTYyBzGjxC1AWpechKEuAg6zcMTspvHdaGtsbSNw73v6etwWqggPogMygwqrg2Qugi6wRJ66mabQhQz7wmb/5FTZU3w55fj095xteO9PhTDPW3wIpzxEm0GW/aZ9fS3EMLKKxGs02EWyhqFQdRNhXLMUB+BVdylDxG3W/Q23dz8lY3svJNLdwSojwjEbpS4DQhZYKO7ce9LW8zq2+39Q8VzwhdY/lPmIXdm66QDzK10A2GO1io5KYm/sU/44diV0RCqiqxQJpkSfl7otaGFVgvHZceRVffCfDIW9qS8r+ZJz2NgmCCG1yuQtKMJVcXuoxy0JIzWp6dZhPV08kv6ls28vmJI00GQLzzUqt/m7jGf9nt42Ag9Tdqj3Z9OFl+0cHUn488okiFD9BJLCFz6qsd6mrzyCmEyrWmed4qHWk47k=
    username: AgB8/E1/q3hzHkptt3WVvGwO0wcV2HUnQ0mggKeO6xmvPVbHen/ITm4jt77vubbtpogXZjqISzt6QjaJrTFIMkitxWd3tdjK1O34KP5S18Zhedtt6V8YaK8ilQz0lenbNprH1OeEOSFZJu06VYNTesHs1QQXAhD2ZtgZDpubvNmNg2/EyTaE1tYnTU0RPzFkCbimKR2puo1RkgzMbbgT2BmaF41pdtuSsc97MhdRNqoq2UGVjLBlYM3d5E4y65UaDoPinL5gULkO8c3kBY9qqLgBHb0bCTiowCto8y+G/XNXcb+xeImNqeQn+pAZuKMINJsGXbGhOONJcrYU+V1DPC5Y8Rn6b1DZdYrpO07r12R5VVv8CW0bHVjeAr3bPilxXLgrUvYIUgNtqUWYZfAmRpDlP2f6ueGv1+IOMoOv162LZvRRXIgfbSegkm4DRhcAyn/NVxnqoOYUOSYG5AT92jIEN5xWV1vyNU4ZuI8kQKhbDZ7la55rk38yvtS7NyaTEkuBhztniApMZwqzPuGwdNwzM6Uwg1BHH8v5dmDiq+zdO1WRxsIu8jKm3UoLRndmXHDD39w60SAvpQkejpgAjI5A2wPi6cCkOdE5uPSzFzAvwTl00xCR12PILd0vYgpZSUbToPThKzAsxPo86NpZHfbVQ3pZ2urlOAxAQITyiCstQxcS/akucR8ytwYQ1BPl4MmB06pcbYo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: git-creds
      namespace: argocd
