apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: apps
  labels:
    app: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: PIHOLE_DNS_
              value: "9.9.9.9;194.242.2.2"
            - name: DNSMASQ_LISTENING
              value: "all"
          ports:
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 80
              protocol: TCP
              name: web
          volumeMounts:
            - name: config
              mountPath: /etc/pihole
              subPath: pihole
            - name: config
              mountPath: /etc/dnsmasq.d
              subPath: dnsmasq.d
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pihole-config
