---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole-secret
  namespace: apps
spec:
  encryptedData:
    WEBPASSWORD: AgB1BqdxVhXsQxDmAbvwONvdxcyeQXWkpdnZpqI5UhxFA9oVgl0wSha4as1ow/UlkLZYTlp1qNWgVJKLdquBZcIM0ESYSVeluLowCuGSXnHQBZKBL4KMqPeEBNiztjo2V2/CrPk+CprqAY+xE64TWPDaBlta300IQsxR2lWr1yWih5Ev8KDdeIx+kz1Rpjzk5rvILOHDFPbWiWRawJGMaa2QobqO3oWA1/5Oeu+bYtdO+w3NcPanbS9KThrM8yRhlwq7b1mSm3z408nSOnLGOLSC7WL1uQzMYt9whC88tkTvMqCB5AJcSwdIkHaDI4Uo2lqBBiaBvLN4U+seIAY+0yFHMvtn6e2bIk9b/XyMMVNvXg0YxV09HK9BSX9tCd9fFclobyKYvdDATSRIbFSUaz9L9zK6QZheK0SIGXiEPDefxEI/6wUy6Cpippl1BFyrPwByvK6lD0O2A2FwqbPzb6RvvsIGf+2JxLmYJdfeollBcrB8zwrMbCzLaLgoHr0KcUUGlvYGRW9aWSqMIIqw/Z50x8QK3j5+18ueAU/mmeUVUIl3a8IYaD7AhyAVE484ZG6yV2lWJo5n4Ou4WYcRrG93TS0WkbNVQfKQhykdVgQ5bA3YYK//Qe00279F7ImGJ7U6MYp7tJOUUasXo8wc+jrxXaWDmOWbVRxFJ86Y2ak4P9EgO5UsbQKBq33eZ1PEJnjWrb1Maz/abBVHhn7b4ohX7WHNAg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pihole-secret
      namespace: apps
