---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole-secret
  namespace: apps
spec:
  encryptedData:
    WEBPASSWORD: AgAcoNf8ctFyRy6h2Ks33Jh91FQPXjRMaXjf3g8e7WbhrNQWBWc6zSxBa1vsHhdDeXO/qvdUInkEf/0ayNW9FWvgPEI2R2Net8motSYK30lN0qigsPdVG3lLABj8Hh13lqhyktZluELM9hIdpvgEY90YwoH/Hzpi+J+IO0qQCZst/GpWGn7Yep57/ZkevsKzXojJJyR/q4Qy7SPK3AXuIIsGFV75Lzpkj1+ws2JCHP3UiYgLvwdBcsZ5o4DTDK66G41R+ZJtqsuT97ZrsfRE7lm0tQ93YzJybQlFEMznmdYGk6Z38tyKguk/Hc0lgS5DxcCslVylqAUWQYpfLbkR+t4/K8/gQp7Use4aWoHoFOU8T+0EUbv//zeYhfIVFIqHaCGdGS+TW9P3SvM65mUTdytnuY5J5q5oR7yAlV78E16YTOJxvavIYRWwEwLQgqUFpnLIZs6KPnX6P/jFzvwBL4PfRZaXcQepMAqyllicZOcoZqHp0u9Qia3VSiX3uJNz//zlvc982NWQvb6O2Crae6o4MUBt8FwG/vzx1HdsyK/xDgplu1wpDc/lG4HF9jNCseCMggqOeJc/5mbWKGuRCuQY3oLO7pdoGO1jzQpjPuLH9upeEbK0QZcd/aCem+4u+hTp+VhV67THt+Y38z29j6MheljvInHQhJt9+pZC+I9JCK71QwNPyThnakp56pEcPKI48wUIdPz4wSI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pihole-secret
      namespace: apps
